CREATE TABLE PRODUCTS (
    ID INTEGER NOT NULL,
    TITLE TEXT,
    DESCRIPTION TEXT,
    PRICE INTEGER,
    CATEGORY_ID INTEGER,
    CREATE_DATE DATE,
    LAST_UPDATE_DATE DATE,
    AMOUNT_IN_STOCK INTEGER,
    SELLER_ID TEXT,
    IS_CONFIRM_FOR_SALE BOOLEAN,
    IMAGE_ID INTEGER
);

CREATE SEQUENCE SEQ_PRODUCTS START 1;
