INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'other', 'Другое');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'hand_made', 'Своими руками');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'antiques', 'Антиквариат');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'books', 'Книги');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'cloth', 'Одежда');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'cars', 'Автомобили');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'shoes', 'Обувь');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'electonics', 'Электроника');
INSERT INTO CATEGORIES(ID, CATEGORY_CODE, CATEGORY_TITLE) VALUES(nextval('SEQ_CATEGORIES'), 'sports', 'Спорт');
