version: '2'
services:

  postgres:
    container_name: postgres-pixo
    image: postgres:15.6
    ports:
      - "54320:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak

  keycloak:
    container_name: keycloak-pixo
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?currentSchema=keycloak
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    command:
      - start-dev

#  postgres-product:
#    container_name: postgres-product
#    image: postgres:15.6
#    ports:
#      - "54321:5431"
#    expose:
#        - "54321"
#    environment:
#      POSTGRES_PASSWORD: admin
#      POSTGRES_USER: admin
#      POSTGRES_DB: product
