version: '2'
services:

  postgres:
    container_name: keycloak-postgres-15
    image: postgres:15.6
    ports:
      - 54320:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pdb

  keycloak:
    container_name: keycloak-24
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/pdb?currentSchema=keycloak
    ports:
      - 8181:8080
    depends_on:
      - postgres
    command:
      - start-dev
