server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/pixo
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
#          gateway: TRACE
          gateway:
            route:
              RouteDefinitionLocator: INFO
