CREATE TABLE ORDER_PRODUCTS (
    ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER,
    ORDER_ID INTEGER,
    AMOUNT INTEGER,
    FINAL_PRICE INTEGER,
    WISHES TEXT
);

CREATE SEQUENCE SEQ_ORDER_PRODUCTS START 1;
